package main

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type ChecksumEntry struct {
	Hash string
	Path string
}

func (r *Runner) WriteReleaseChecksums() error {
	r.PrintHeader("write-checksums")

	fmt.Printf("release_package_root: %s\n", r.UmbrellaRoot)

	releaseDir := filepath.Join(r.UmbrellaRoot, "release")
	if err := os.MkdirAll(releaseDir, 0755); err != nil {
		return err
	}

	entries, err := r.collectChecksumEntries()
	if err != nil {
		return err
	}

	checksumPath := filepath.Join(releaseDir, "checksums.txt")

	var b strings.Builder
	b.WriteString("# CarbonStack release package checksums\n")
	b.WriteString("# Format: sha256  relative/path/from/package/root\n")
	b.WriteString("# Generated by carbonstack/tools/carbonstack-validate\n")

	for _, entry := range entries {
		b.WriteString(entry.Hash)
		b.WriteString("  ")
		b.WriteString(entry.Path)
		b.WriteString("\n")
	}

	if err := os.WriteFile(checksumPath, []byte(b.String()), 0644); err != nil {
		return err
	}

	fmt.Printf("wrote checksum file: %s\n", checksumPath)
	fmt.Printf("checksum entries: %d\n", len(entries))

	return nil
}

func (r *Runner) VerifyReleaseChecksums() error {
	fmt.Println()
	fmt.Println("== Release checksum verification ==")

	checksumPath := filepath.Join(r.UmbrellaRoot, "release", "checksums.txt")

	file, err := os.Open(checksumPath)
	if err != nil {
		return fmt.Errorf("open checksum file: %w", err)
	}
	defer file.Close()

	var entries []ChecksumEntry
	scanner := bufio.NewScanner(file)

	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())

		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		entry, err := parseChecksumLine(line, lineNumber)
		if err != nil {
			return err
		}

		entries = append(entries, entry)
	}

	if err := scanner.Err(); err != nil {
		return err
	}

	if len(entries) == 0 {
		return fmt.Errorf("checksum file has no entries")
	}

	expectedEntries, err := r.collectChecksumEntries()
	if err != nil {
		return err
	}

	expectedByPath := map[string]string{}
	for _, entry := range expectedEntries {
		expectedByPath[entry.Path] = entry.Hash
	}

	seen := map[string]bool{}

	for _, entry := range entries {
		expectedHash, ok := expectedByPath[entry.Path]
		if !ok {
			return fmt.Errorf("checksum entry references unexpected or excluded file: %s", entry.Path)
		}

		if expectedHash != entry.Hash {
			return fmt.Errorf("checksum mismatch for %s: expected %s got %s", entry.Path, expectedHash, entry.Hash)
		}

		seen[entry.Path] = true
		fmt.Printf("OK CHECKSUM: %s\n", entry.Path)
	}

	var missing []string
	for path := range expectedByPath {
		if !seen[path] {
			missing = append(missing, path)
		}
	}

	sort.Strings(missing)

	if len(missing) > 0 {
		for _, path := range missing {
			fmt.Printf("MISSING CHECKSUM: %s\n", path)
		}
		return fmt.Errorf("checksum file missing %d expected file(s)", len(missing))
	}

	fmt.Printf("checksum verification passed: %d file(s)\n", len(entries))
	return nil
}

func parseChecksumLine(line string, lineNumber int) (ChecksumEntry, error) {
	if len(line) < 66 {
		return ChecksumEntry{}, fmt.Errorf("invalid checksum line %d: expected '<64-hex-sha256>  <relative-path>'", lineNumber)
	}

	hash := strings.ToLower(strings.TrimSpace(line[:64]))
	rel := strings.TrimSpace(line[64:])
	rel = filepath.ToSlash(rel)

	if len(hash) != 64 {
		return ChecksumEntry{}, fmt.Errorf("invalid checksum line %d: sha256 length should be 64 hex characters", lineNumber)
	}

	for _, c := range hash {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			return ChecksumEntry{}, fmt.Errorf("invalid checksum line %d: sha256 contains non-hex character", lineNumber)
		}
	}

	if rel == "" {
		return ChecksumEntry{}, fmt.Errorf("invalid checksum line %d: missing relative path", lineNumber)
	}

	if strings.HasPrefix(rel, "/") || strings.Contains(rel, "../") || strings.Contains(rel, `\`) {
		return ChecksumEntry{}, fmt.Errorf("invalid checksum line %d: unsafe relative path %q", lineNumber, rel)
	}

	return ChecksumEntry{Hash: hash, Path: rel}, nil
}

func (r *Runner) collectChecksumEntries() ([]ChecksumEntry, error) {
	var entries []ChecksumEntry

	err := filepath.WalkDir(r.UmbrellaRoot, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}

		name := d.Name()

		if d.IsDir() {
			if shouldSkipChecksumDir(name) {
				return filepath.SkipDir
			}
			return nil
		}

		if shouldSkipChecksumFile(path, name, r.UmbrellaRoot) {
			return nil
		}

		rel, err := filepath.Rel(r.UmbrellaRoot, path)
		if err != nil {
			return err
		}

		rel = filepath.ToSlash(rel)

		hash, err := sha256File(path)
		if err != nil {
			return err
		}

		entries = append(entries, ChecksumEntry{
			Hash: hash,
			Path: rel,
		})

		return nil
	})

	if err != nil {
		return nil, err
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Path < entries[j].Path
	})

	return entries, nil
}

func shouldSkipChecksumDir(name string) bool {
	switch name {
	case ".git", "target", ".carbonstack-openmls-sidecar-state", ".go-cache", ".go-tmp":
		return true
	default:
		return false
	}
}

func shouldSkipChecksumFile(path string, name string, root string) bool {
	rel, err := filepath.Rel(root, path)
	if err == nil {
		rel = filepath.ToSlash(rel)
		if rel == "release/checksums.txt" {
			return true
		}
	}

	switch name {
	case "provider-storage.json", "signer.json", "Thumbs.db", ".DS_Store":
		return true
	}

	suffixes := []string{
		".db",
		".db-shm",
		".db-wal",
		".exe",
		".test.exe",
		".tgz",
		".tar.gz",
		".tar",
		".zip",
	}

	for _, suffix := range suffixes {
		if strings.HasSuffix(name, suffix) {
			return true
		}
	}

	return false
}

func sha256File(path string) (string, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer file.Close()

	h := sha256.New()
	if _, err := io.Copy(h, file); err != nil {
		return "", err
	}

	return hex.EncodeToString(h.Sum(nil)), nil
}
